config/routes.rb
Cmov2Server::Application.routes.draw do
  resources :users do
    collection do
      post 'update_registration'
    end
  end

  resources :properties do 
    member do
      get 'short'
      get 'long'
      post 'discard'
    end
    collection do
      get 'items'
    end
  end

end

app/models/discarded_property.rb
class DiscardedProperty < ActiveRecord::Base
  belongs_to :property
  belongs_to :user
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :discarded_properties
  has_many :users, :through => :discarded_properties
  
  has_attached_file :photo, :styles => { :small => "100x100", :normal => "400x400" }
  
  TYPES = ["apartment", "castle", "home"]
  
  STATES = ["for sale", "sold"]
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :discarded_properties
  has_many :properties, :through => :discarded_properties
  
  def items
    Property.find_by_sql ['SELECT "properties".* FROM "properties"
                          WHERE "properties"."state" = "for sale" AND id NOT IN
                                (SELECT "discarded_properties"."property_id" FROM "discarded_properties" 
                                WHERE "discarded_properties"."user_id" = ?)', self.id ]
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        users = User.all
        users.each { |u|
          options = {
            :registration_id => u.registration_id,
            :message => "New property added to Property Market!",
            :id => @property.id,
            :name => @property.name,
            :ptype => @property.ptype,
            :collapse_key => @property.id.to_s
          }
          puts options.inspect
          response = SpeedyC2DM::API.send_notification(options)
          puts response.inspect
        }
        

        
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :ok }
    end
  end
  
  def short
    @property = Property.find(params[:id])
    formatted_json = {
        :id => @property.id,
        :name => @property.name,
        :type => @property.ptype,
        :price => @property.price,
        :photo => @property.photo.url(:small)
      }
    respond_to do |format|
      format.json { render :json => formatted_json }
    end    
  end
  
  def long
    @property = Property.find(params[:id])
    formatted_json = {
        :id => @property.id,
        :name => @property.name,
        :type => @property.ptype,
        :price => @property.price,
        :photo => @property.photo.url(:normal),
        :address => @property.address,
        :city => @property.city,
        :description => @property.description,
        :created_at => @property.created_at,
        :state => @property.state 
      }
    respond_to do |format|
      format.json { render :json => formatted_json }
    end    
  end
  
  def items
    user = User.find_by_email(params[:user_email])
        
    formatted_json = []
    user.items.each { |p| 
      formatted_json << {
        :id => p.id,
        :name => p.name,
        :type => p.ptype,
        :price => p.price,
        :photo => p.photo.url(:small)
      }
    }
    respond_to do |format|
      format.json { render :json => formatted_json }
    end    
  end
  
  def discard
    user = User.find_by_email(params[:user_email])
    dp = DiscardedProperty.new(:user_id => user.id, :property_id => params[:id])
    dp.save
    respond_to do |format|
      format.json { head :ok }
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
  
  def update_registration
    @user = User.find_or_create_by_email(params[:email])
    @user.registration_id = params[:registration_id]

    respond_to do |format|
      if @user.save
        format.json { render json: @user, status: :created, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cmov2Server</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/properties/_form.html.erb
<%= form_for @property, :html => { :multipart => true } do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= select("property", "ptype", Property::TYPES) %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= select("property", "state", Property::STATES) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Listing properties</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Photo</th>
    <th>Type</th>
    <th>Address</th>
    <th>City</th>
    <th>Description</th>
    <th>Price</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.name %></td>
    <td><%= image_tag property.photo.url(:normal) %></td>
    <td><%= property.ptype %></td>
    <td><%= property.address %></td>
    <td><%= property.city %></td>
    <td><%= property.description %></td>
    <td><%= property.price %></td>
    <td><%= property.state %></td>
    <td><%= link_to 'Show', property %></td>
    <td><%= link_to 'Edit', edit_property_path(property) %></td>
    <td><%= link_to 'Destroy', property, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @property.name %>
</p>

<p>
  <b>Photo:</b>
  <%= image_tag @property.photo.url(:normal) %>
</p>

<p>
  <b>Type:</b>
  <%= @property.ptype %>
</p>

<p>
  <b>Address:</b>
  <%= @property.address %>
</p>

<p>
  <b>City:</b>
  <%= @property.city %>
</p>

<p>
  <b>Description:</b>
  <%= @property.description %>
</p>

<p>
  <b>Price:</b>
  <%= @property.price %>
</p>

<p>
  <b>State:</b>
  <%= @property.state %>
</p>


<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :registration_id %><br />
    <%= f.text_field :registration_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Registration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.registration_id %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<p>
  <b>Registration:</b>
  <%= @user.registration_id %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>